-- AlterTable
ALTER TABLE "breeds" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(2),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(2);

-- AlterTable
ALTER TABLE "prices" ALTER COLUMN "service_id" SET DEFAULT 'NULL',
ALTER COLUMN "breed_id" SET DEFAULT 'NULL',
ALTER COLUMN "size" SET DEFAULT 0,
ALTER COLUMN "weight" SET DEFAULT 0,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(2),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(2);

-- AlterTable
ALTER TABLE "service_categories" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(2),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(2);

-- AlterTable
ALTER TABLE "services" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(2),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(2);
